---
- hosts: logsource
  gather_facts: no
  sudo: yes
  vars:
    conf_file: /etc/syslog-ng/syslog-ng.conf
    source_name: source s_logfile
    destination_name: destination d_logserver
  tasks:
    - name: Add file source
      lineinfile:
        dest={{ conf_file }}
        line="{{ source_name }} { file(\"{{ log_file }}\" flags(no-parse)); };"
        regexp="^{{ source_name }} "
        state=present
        insertafter=EOF
    - name: Add tcp destination 
      lineinfile:
        dest={{ conf_file }}
        line="{{ destination_name }} { tcp(\"{{ log_dest_host }}\" port({{ log_dest_port }})); };"
        regexp="^{{ destination_name }} "
        state=present
        insertafter=EOF
    - name: Add log statement to link source to destination
      lineinfile:
        dest={{ conf_file }}
        line="log { source(s_logfile); destination(d_logserver); };"
        state=present
        insertafter=EOF
    - name: Restart syslog-ng service
      service: name=syslog-ng state=restarted
...
